sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

before_install: luarocks install --local luacheck

script: /home/travis/.luarocks/bin/luacheck *.lua

notifications:
  email:
    on_success: never
    on_failure: always
